apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: dev-k8s-secretstore
    kind: SecretStore
  target:
    name: demo-app-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: demo-app-shared
      property: username
  - secretKey: password
    remoteRef:
      key: demo-app-shared
      property: password
