apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dev-k8s-secretstore
spec:
  provider:
    kubernetes:
      remoteNamespace: shared-secrets
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: external-secrets-reader
