apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dev-app
  namespace: argocd
spec:
  project: team-dev
  source:
    repoURL: https://github.com/shubhamsugara22/Kleptic-tools
    targetRevision: main
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
