apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-prod-app
  namespace: argocd
spec:
  project: team-prod
  source:
    repoURL: https://github.com/shubhamsugara22/Kleptic-tools
    targetRevision: main
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-sample
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
