apiVersion: 1
groups:
  - orgId: 1
    name: Loki stack health
    folder: Infrastructure
    interval: 1m
    rules:
      - uid: promtail-down
        title: Promtail Down
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: up{job="promtail"}
              instant: true
              range: false
              refId: A
          - refId: C
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        for: 2m
        noDataState: Alerting
        execErrState: Alerting
        labels:
          severity: warning
        annotations:
          summary: Promtail target is down
