apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  labels:
    app: demo-app
    environment: prod
data:
  APP_NAME: demo-app
  ENVIRONMENT: prod
  MESSAGE: Day 2 ApplicationSet deployment for prod (manual sync)
